################################################################
#
# Copyright (c) 2016-2017 EnterpriseDB - All rights reserved.
#
################################################################

# Prerequisite: Environment variables EDBYUMUSERNAME and EDBYUMPASSWORD must be set up on the Ansible Controller 

# Usage: ansible-playbook prereqs/2-edb-prereqs.edb_repo_configure.yml --extra-vars "host=ansible-tests"

- hosts: "{{ host }}"
  vars:
    yumusername:  "{{ lookup('env','EDBYUMUSERNAME') }}"
    yumpassword: "{{ lookup('env','EDBYUMPASSWORD') }}"
        
  tasks:
  - name: Update edb.repo with YUM repository credentials
    replace:
      path: "{{ item.path }}"
      regexp: "{{ item.regexp1 }}"
      replace: "{{ item.replace }}"
    with_items:
      - { path: '/etc/yum.repos.d/edb.repo', regexp1: <username>, replace: "{{ yumusername }}" }
      - { path: '/etc/yum.repos.d/edb.repo', regexp1: <password>, replace: "{{ yumpassword}}" }
