# Usage:  ansible-playbook epas/edb-as.config_epas-for-logical-replication.yml -i inventory.ini --extra-vars "host=epas1 pgmajor=11"

- hosts: epas-masters
  become: yes
  become_user: root
  become_method: sudo
  vars:
        asmajor: "{{ pgmajor | default(11) }}"

  tasks:
    - name: Add Best Practices for logging
      blockinfile:
        dest: /var/lib/edb/as{{ asmajor }}/data/edb_best_practices_params.conf
        marker: "# {mark} Ansible Managed Logical Replication Parameters"
        block: |
          wal_level = logical
          max_wal_senders = 10
          max_replication_slots = 10
          track_commit_timestamp = on