# Usage:  Usage: ansible-playbook epas/edb-as-restart-epas.yml -i inventory.ini --extra-vars "host=epas1 pgmajor=11" 
- hosts: "{{ host }}"
  become: yes
  become_user: root
  become_method: sudo
  vars:
        asmajor: "{{ pgmajor | default(11) }}"

  tasks:
    - name: Restarting EPAS
      systemd:
        name: edb-as-{{ asmajor }}.service
        state: restarted
        enabled: yes