# Usage: ansible-playbook edb-as-02.initialize_epas.yml --extra-vars "host=ansible-tests pgdata=/opt/edb/pgdata pgwal=/opt/edb/pgwal pgmajor=11"
# PGDATA and PGWAL are optional

- hosts: epas-all
  become: true
  become_user: root
  become_method: sudo
  vars:
        asmajor: "{{ pgmajor | default(11) }}"
        aspgdata: "{{ pgdata | default('/var/lib/edb/as'+asmajor+'/data') }}"

  tasks:
    - name: Check if PGDATA is empty
      stat:
        path: "{{ pgdata if pgdata is defined else aspgdata }}/PG_VERSION"
      register: PG_VERSION
      become: true
      become_user: enterprisedb
      become_method: sudo

    - name: Create PGDATA direcotry
      file:
        path: "{{ aspgdata }}"
        state: directory
        owner: enterprisedb
        group: enterprisedb
        mode: 0700

    - name: Create PGWAL directory
      file:
        path: "{{ pgwal }}"
        state: directory
        owner: enterprisedb
        group: enterprisedb
        mode: 0700
      when: pgwal is defined

    #TODO Combine the following into one command, add options
    - name: Initialize EPAS with custom PGWAL
      shell: /usr/edb/as{{ asmajor }}/bin/initdb --waldir="{{ pgwal }}" --pgdata="{{ aspgdata }}"
      when: pgwal is defined and not PG_VERSION.stat.exists
      become: true
      become_user: enterprisedb
      become_method: sudo

    - name: Initialize EPAS with PGDATA and WAL located inside PGDATA 
      shell: /usr/edb/as{{ asmajor }}/bin/initdb --pgdata={{ aspgdata }}
      when: pgwal is undefined and not PG_VERSION.stat.exists
      become: true
      become_user: enterprisedb
      become_method: sudo

    - stat:
        path: "/var/lib/edb/as{{ asmajor }}/data"
      register: pgdatalnk

    - name: Remove default PGDATA directory
      file:
        path: "/var/lib/edb/as{{ asmajor }}/data/"
        state: absent
      when: pgdata is defined and not pgdatalnk.stat.islnk

    - name: Create symbolic link from default PGDATA to custom to PGDATA (useful for running EPAS with system service)
      file:
        src: "{{ pgdata }}"
        path: /var/lib/edb/as{{ asmajor }}/data
        owner: enterprisedb
        group: enterprisedb
        state: link
        mode: 0700
      when: pgdata is defined

    - debug:
        msg: "edb-as-{{ asmajor }}" 
    - name: Starting EPAS as a system service...
      systemd:
        name: "edb-as-{{ asmajor }}"
        state: started
        enabled: yes
