# Usage: ansible-playbook eprs/edb-rs-03.start_eprs7.yml -i inventory.ini

- hosts: eprs-all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Starting EPRS7 as a system service
      systemd:
        name: edb-rs-server.service
        state: started
        enabled: yes