################################################################
#
# Copyright (c) 2016-2017 EnterpriseDB - All rights reserved.
#
################################################################

# Usage:  ansible-playbook edb-rs-03.start_eprs7.yml --extra-vars "host=ansible-tests"

- hosts: "{{ host }}"

  tasks:
    - name: Starting EPRS7 as a system service
      systemd:
        name: edb-rs-server.service
        state: started
        enabled: yes